<?php

//escape strings
$DATE = mysqli_real_escape_string($link, $_REQUEST['DATE']);
$SLIT_OP = mysqli_real_escape_string($link, $_REQUEST['SLIT_OP']);
$ROLL_DIAMETER = mysqli_real_escape_string($link, $_REQUEST['ROLL_DIAMETER']);
$STRIP_LENGTH_FEET = mysqli_real_escape_string($link, $_REQUEST['STRIP_LENGTH_FEET']);
$COMBINED_SERIAL = mysqli_real_escape_string($link, $_REQUEST['COMBINED_SERIAL']);
$NOTES = mysqli_real_escape_string($link, $_REQUEST['NOTES']);
$TIMESTAMP = mysqli_real_escape_string($link, $_REQUEST['TIMESTAMP']);
$ELECTRODE_SERIAL_1 = mysqli_real_escape_string($link, $_REQUEST['ELECTRODE_SERIAL_1']);
$ELECTRODE_LENGTH_1 = mysqli_real_escape_string($link, $_REQUEST['ELECTRODE_LENGTH_1']);
$ELECTRODE_SERIAL_2 = mysqli_real_escape_string($link, $_REQUEST['ELECTRODE_SERIAL_2']);
$ELECTRODE_LENGTH_2 = mysqli_real_escape_string($link, $_REQUEST['ELECTRODE_LENGTH_2']);
$ELECTRODE_SERIAL_3 = mysqli_real_escape_string($link, $_REQUEST['ELECTRODE_SERIAL_3']);
$ELECTRODE_LENGTH_3 = mysqli_real_escape_string($link, $_REQUEST['ELECTRODE_LENGTH_3']);
$PERFORATED = mysqli_real_escape_string($link, $_REQUEST['PERFORATED']);
if(empty($ELECTRODE_SERIAL_1) ===! true){
$COMBINED_SERIAL = $ELECTRODE_SERIAL_1 ;
	if($PERFORATED === "1"){
	$COMBINED_SERIAL = $COMBINED_SERIAL ."-PF";
	$ELECTRODE_SERIAL_1 = $ELECTRODE_SERIAL_1 ."-PF";
	}

} else{
echo "ERROR: No serial number entered!!!";
}
if(empty($ELECTRODE_SERIAL_2) ===! true){
$COMBINED_SERIAL = $COMBINED_SERIAL ."/". $ELECTRODE_SERIAL_2 ;
	if($PERFORATED === "1"){
	$COMBINED_SERIAL = $COMBINED_SERIAL ."-PF";
	$ELECTRODE_SERIAL_2 = $ELECTRODE_SERIAL_2 ."-PF";
	} else{
	}
}
if(empty($ELECTRODE_SERIAL_3) ===! true){
$COMBINED_SERIAL = $COMBINED_SERIAL ."/". $ELECTRODE_SERIAL_3 ;
if($PERFORATED === "1"){
	$COMBINED_SERIAL = $COMBINED_SERIAL ."-PF";
	$ELECTRODE_SERIAL_3 = $ELECTRODE_SERIAL_3 ."-PF";
	}
}

$DATE = date("m/d/Y");
$TIMESTAMP = date("m/d/Y-H:i:s");
$STRIP_LENGTH_FEET = $ELECTRODE_LENGTH_1 + $ELECTRODE_LENGTH_2 + $ELECTRODE_LENGTH_3;
$STRIP_LENGTH_METERS = round($STRIP_LENGTH_FEET / 3.28084);
$ELECTRODE_AREA = $STRIP_LENGTH_METERS / 4;
$NUM_DEFECTS = $NUM_HOLES + $NUM_DELAM + $NUM_SPLICE;

//SQL Insert Statement
$sql = "INSERT INTO SLITTER (DATE, SLIT_OP, COMBINED_SERIAL, STRIP_LENGTH_FEET, STRIP_LENGTH_METERS, ELECTRODE_AREA, NUM_DEFECTS, NUM_HOLES, NUM_DELAM, NUM_SPLICE, PERFORATED, NOTES, TIMESTAMP) VALUES ('$DATE','$SLIT_OP','$COMBINED_SERIAL','$STRIP_LENGTH_FEET','$STRIP_LENGTH_METERS','$ELECTRODE_AREA','$NUM_DEFECTS','$NUM_HOLES','$NUM_DELAM','$NUM_SPLICE','$PERFORATED','$NOTES','$TIMESTAMP')";

$inventory_sql = "INSERT INTO INVENTORY_ELECTRODE.ELECTRODE_INVENTORY (COMBINED_SERIAL, LENGTH, LOCATION, TIMESTAMP) VALUES ('$COMBINED_SERIAL','$STRIP_LENGTH_METERS','$LOCATION','$TIMESTAMP')";

if(mysqli_query($link, $sql)){
echo "Records added successfully.";
}
?>
